config/routes.rb
Zabbix::Application.routes.draw do
  resources :items
  resources :groups
  resources :applications
  resources :hosts

  resources :screens
  resources :graphs do 
    member do
      get "data"
    end
  end

  devise_for :users

end

app/models/action.rb
class Action < ActiveRecord::Base
  set_primary_key "actionid"
  has_many :conditions, :foreign_key => "actionid"
end

app/models/application.rb
class Application < ActiveRecord::Base
  set_primary_key "applicationid"
  belongs_to :host, :foreign_key => "hostid"
end

app/models/condition.rb
class Condition < ActiveRecord::Base
  set_primary_key "conditionid"
  belongs_to :action, :foreign_key => "actionid"
end

app/models/graph.rb
class Graph < ActiveRecord::Base
  set_primary_key "graphid"
  has_many :items, :class_name => "GraphItem", :foreign_key => "graphid"
end

app/models/graph_item.rb
class GraphItem < ActiveRecord::Base
  set_table_name "graphs_items"
  set_primary_key "gitemid"
  set_inheritance_column :ruby_type

  belongs_to :graph, :foreign_key => "graphid"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/group.rb
class Group < ActiveRecord::Base
  set_primary_key "groupid"
  has_many :hosts_groups, :foreign_key => "groupid"
  has_many :hosts, :through => :hosts_groups
end

app/models/history.rb
class History < ActiveRecord::Base
  set_table_name "history"
  set_primary_key "itemid"
  belongs_to :item, :foreign_key => "itemid"

end

app/models/history_log.rb
class HistoryLog < ActiveRecord::Base
  set_table_name "history_log"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/host.rb
class Host < ActiveRecord::Base
  set_primary_key "hostid"
  has_many :applications, :foreign_key => "hostid"
  has_many :hosts_groups, :foreign_key => "hostid"
  has_many :groups, :through => :hosts_groups
  has_many :hosts_templates, :foreign_key => "hostid"
  has_many :templates, :through => :hosts_templates
  has_many :items, :foreign_key => "hostid"

  alias_attribute :name, :host
end

app/models/hosts_group.rb
class HostsGroup < ActiveRecord::Base
  set_primary_key "hostgroupid"
  belongs_to :host, :foreign_key => "hostid"
  belongs_to :group, :foreign_key => "groupid"
end

app/models/hosts_template.rb
class HostsTemplate < ActiveRecord::Base
  set_primary_key "hosttemplateid"
  belongs_to :host, :foreign_key => "hostid"
  belongs_to :template, :class_name => "Host", :foreign_key => "templateid"
end

app/models/item.rb
class Item < ActiveRecord::Base
  set_primary_key "itemid"
  set_inheritance_column :ruby_type

  belongs_to :host, :foreign_key => "hostid"
  has_many :items_applications, :foreign_key => "itemid"
  has_many :applications, :through => :items_applications

  has_many :history, :class_name => "History", :foreign_key => "itemid"
  has_many :trends, :class_name => "Trend", :foreign_key => "itemid"
  has_many :trends_uint, :class_name => "TrendUint", :foreign_key => "itemid"
  has_many :history_logs, :foreign_key => "itemid"
end

app/models/items_application.rb
class ItemsApplication < ActiveRecord::Base
  set_primary_key "itemappid"
  belongs_to :application, :foreign_key => "applicationid"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/screen.rb
class Screen < ActiveRecord::Base
  set_primary_key "screenid"
  has_many :items, :class_name => "ScreenItem", :foreign_key => "screenid"
end

app/models/screen_item.rb
class ScreenItem < ActiveRecord::Base
  set_table_name "screens_items"
  set_primary_key "screenitemid"
  belongs_to :screen, :foreign_key => "screenid"
end

app/models/trend.rb
class Trend < ActiveRecord::Base
  set_table_name "trends"
  set_primary_key "itemid"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/trend_uint.rb
class TrendUint < ActiveRecord::Base
  set_table_name "trends_uint"
  set_primary_key "itemid"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable

  # :registerable
  devise :database_authenticatable, :encryptable, :encryptor => :md5
  #       :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login, :password, :password_confirmation, :remember_me

  def login
    read_attribute(:alias)
  end

  def login=(value)
    write_attribute(:alias, value)
  end

  def password=(new_password)
    @password = new_password
    #self.encrypted_password = password_digest(@password) if @password.present?
  end

  def encripted_password
    passwd
  end

  def password_salt
    'ashaks'
  end

  def valid_password?(password)
    Devise.secure_compare(password_digest(incoming_password), self.passwd)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  #before_filter :authenticate_user!
 
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.xml
  def index
    @applications = Application.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.xml
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.xml
  def new
    @application = Application.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.xml
  def create
    @application = Application.new(params[:application])

    respond_to do |format|
      if @application.save
        format.html { redirect_to(@application, :notice => 'Application was successfully created.') }
        format.xml  { render :xml => @application, :status => :created, :location => @application }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @application.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.xml
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to(@application, :notice => 'Application was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @application.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.xml
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to(applications_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :host_id %><br />
    <%= f.text_field :host_id %>
  </div>
  <div class="field">
    <%= f.label :template_id %><br />
    <%= f.text_field :template_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Host</th>
    <th>Template</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applications.each do |application| %>
  <tr>
    <td><%= application.name %></td>
    <td><%= application.host_id %></td>
    <td><%= application.template_id %></td>
    <td><%= link_to 'Show', application %></td>
    <td><%= link_to 'Edit', edit_application_path(application) %></td>
    <td><%= link_to 'Destroy', application, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @application.name %>
</p>

<p>
  <b>Host:</b>
  <%= @application.host_id %>
</p>

<p>
  <b>Template:</b>
  <%= @application.template_id %>
</p>


<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>