config/routes.rb
Zabbix::Application.routes.draw do
  resources :items
  resources :groups
  resources :applications
  resources :hosts

  resources :screens
  resources :graphs do 
    member do
      get "data"
    end
  end

  devise_for :users

end

app/models/action.rb
class Action < ActiveRecord::Base
  set_primary_key "actionid"
  has_many :conditions, :foreign_key => "actionid"
end

app/models/application.rb
class Application < ActiveRecord::Base
  set_primary_key "applicationid"
  belongs_to :host, :foreign_key => "hostid"
end

app/models/condition.rb
class Condition < ActiveRecord::Base
  set_primary_key "conditionid"
  belongs_to :action, :foreign_key => "actionid"
end

app/models/graph.rb
class Graph < ActiveRecord::Base
  set_primary_key "graphid"
  has_many :items, :class_name => "GraphItem", :foreign_key => "graphid"
end

app/models/graph_item.rb
class GraphItem < ActiveRecord::Base
  set_table_name "graphs_items"
  set_primary_key "gitemid"
  set_inheritance_column :ruby_type

  belongs_to :graph, :foreign_key => "graphid"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/group.rb
class Group < ActiveRecord::Base
  set_primary_key "groupid"
  has_many :hosts_groups, :foreign_key => "groupid"
  has_many :hosts, :through => :hosts_groups
end

app/models/history.rb
class History < ActiveRecord::Base
  set_table_name "history"
  set_primary_key "itemid"
  belongs_to :item, :foreign_key => "itemid"

end

app/models/history_log.rb
class HistoryLog < ActiveRecord::Base
  set_table_name "history_log"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/host.rb
class Host < ActiveRecord::Base
  set_primary_key "hostid"
  has_many :applications, :foreign_key => "hostid"
  has_many :hosts_groups, :foreign_key => "hostid"
  has_many :groups, :through => :hosts_groups
  has_many :hosts_templates, :foreign_key => "hostid"
  has_many :templates, :through => :hosts_templates
  has_many :items, :foreign_key => "hostid"

  alias_attribute :name, :host
end

app/models/hosts_group.rb
class HostsGroup < ActiveRecord::Base
  set_primary_key "hostgroupid"
  belongs_to :host, :foreign_key => "hostid"
  belongs_to :group, :foreign_key => "groupid"
end

app/models/hosts_template.rb
class HostsTemplate < ActiveRecord::Base
  set_primary_key "hosttemplateid"
  belongs_to :host, :foreign_key => "hostid"
  belongs_to :template, :class_name => "Host", :foreign_key => "templateid"
end

app/models/item.rb
class Item < ActiveRecord::Base
  set_primary_key "itemid"
  set_inheritance_column :ruby_type

  belongs_to :host, :foreign_key => "hostid"
  has_many :items_applications, :foreign_key => "itemid"
  has_many :applications, :through => :items_applications

  has_many :history, :class_name => "History", :foreign_key => "itemid"
  has_many :trends, :class_name => "Trend", :foreign_key => "itemid"
  has_many :trends_uint, :class_name => "TrendUint", :foreign_key => "itemid"
  has_many :history_logs, :foreign_key => "itemid"
end

app/models/items_application.rb
class ItemsApplication < ActiveRecord::Base
  set_primary_key "itemappid"
  belongs_to :application, :foreign_key => "applicationid"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/screen.rb
class Screen < ActiveRecord::Base
  set_primary_key "screenid"
  has_many :items, :class_name => "ScreenItem", :foreign_key => "screenid"
end

app/models/screen_item.rb
class ScreenItem < ActiveRecord::Base
  set_table_name "screens_items"
  set_primary_key "screenitemid"
  belongs_to :screen, :foreign_key => "screenid"
end

app/models/trend.rb
class Trend < ActiveRecord::Base
  set_table_name "trends"
  set_primary_key "itemid"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/trend_uint.rb
class TrendUint < ActiveRecord::Base
  set_table_name "trends_uint"
  set_primary_key "itemid"
  belongs_to :item, :foreign_key => "itemid"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable

  # :registerable
  devise :database_authenticatable, :encryptable, :encryptor => :md5
  #       :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login, :password, :password_confirmation, :remember_me

  def login
    read_attribute(:alias)
  end

  def login=(value)
    write_attribute(:alias, value)
  end

  def password=(new_password)
    @password = new_password
    #self.encrypted_password = password_digest(@password) if @password.present?
  end

  def encripted_password
    passwd
  end

  def password_salt
    'ashaks'
  end

  def valid_password?(password)
    Devise.secure_compare(password_digest(incoming_password), self.passwd)
  end

end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  # GET /hosts
  # GET /hosts.xml
  def index
    @hosts = Host.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @hosts }
    end
  end

  # GET /hosts/1
  # GET /hosts/1.xml
  def show
    @host = Host.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @host }
    end
  end

  # GET /hosts/new
  # GET /hosts/new.xml
  def new
    @host = Host.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @host }
    end
  end

  # GET /hosts/1/edit
  def edit
    @host = Host.find(params[:id])
  end

  # POST /hosts
  # POST /hosts.xml
  def create
    @host = Host.new(params[:host])

    respond_to do |format|
      if @host.save
        format.html { redirect_to(@host, :notice => 'Host was successfully created.') }
        format.xml  { render :xml => @host, :status => :created, :location => @host }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @host.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hosts/1
  # PUT /hosts/1.xml
  def update
    @host = Host.find(params[:id])

    respond_to do |format|
      if @host.update_attributes(params[:host])
        format.html { redirect_to(@host, :notice => 'Host was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @host.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.xml
  def destroy
    @host = Host.find(params[:id])
    @host.destroy

    respond_to do |format|
      format.html { redirect_to(hosts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :dns %><br />
    <%= f.text_field :dns %>
  </div>
  <div class="field">
    <%= f.label :useip %><br />
    <%= f.check_box :useip %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :port %><br />
    <%= f.text_field :port %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<h1>Listing hosts</h1>

<table>
  <tr>
    <th>Host</th>
    <th>Dns</th>
    <th>Useip</th>
    <th>Ip</th>
    <th>Port</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hosts.each do |host| %>
  <tr>
    <td><%= host.host %></td>
    <td><%= host.dns %></td>
    <td><%= host.useip %></td>
    <td><%= host.ip %></td>
    <td><%= host.port %></td>
    <td><%= host.status %></td>
    <td><%= link_to 'Show', host %></td>
    <td><%= link_to 'Edit', edit_host_path(host) %></td>
    <td><%= link_to 'Destroy', host, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Host', new_host_path %>

app/views/hosts/new.html.erb
<h1>New host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Host:</b>
  <%= @host.host %>
</p>

<p>
  <b>Dns:</b>
  <%= @host.dns %>
</p>

<p>
  <b>Useip:</b>
  <%= @host.useip %>
</p>

<p>
  <b>Ip:</b>
  <%= @host.ip %>
</p>

<p>
  <b>Port:</b>
  <%= @host.port %>
</p>

<p>
  <b>Status:</b>
  <%= @host.status %>
</p>


<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>